# Cấu hình cho n8n
# N8N_WEBHOOK_URL = "http://localhost:5678/webhook/56ae0a3a-f79c-4568-baf4-bd4dbc05b5cd" # Ollama hosting
N8N_WEBHOOK_URL = "http://localhost:5678/webhook/a5d280ae-22b9-44f2-a43a-c2429efd2825" # Google AI studio

# Hoặc nếu dùng Dify self-hosted:
DIFY_API_URL = "http://localhost/v1/chat-messages"
DIFY_API_KEY = "app-u6S3A0WwaJt1C43CPcKLlW1X"